export default {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
};
// export default {
//     BasicSidebar: [
//       {
//         type: 'category',
//         label: 'Overview',
//         items: [
//           'overview',
//           'overview/test',
//         ]
//       }
//     ]
//   };